### ISSUE TITLE
missing documentation on required fasta files

### ISSUE THREAD

**Issue by xpastor** [jewmanchue/wham#13]
Hi,

when trying to run Wham it showed a FATAL error regarding to a lack of fasta file. In the documentation provided it's not specified that a fasta file may be provided (actually it's a requirement).
I could find out how to provide the file checking the code (-f). I guess it's a forget due to Wham still being under development.

Best,
Xavier

**Comment by jewmanchue** [comment]
Xavier,

Thank you for catching this.  I've pushed the fix into master.  Please let me know if you find any other bugs, have suggestions, or complaints.

--Zev
