### ISSUE TITLE
Genotyping

### ISSUE THREAD

**Issue by woodoo46** [jewmanchue/wham#45]
Hi,

Just a quick question, wham does not provide genotyping step itself? We need to use another program to genotype wham's result?

Thanks.

George

**Comment by zeeev** [comment]
Hello,

Yes, I'de recommend you use SVTyper for whamg SV calls.

**Comment by zeeev** [comment]
Hello,

Yes, I'd recommend SVTyper for WhamG calls.

**Comment by woodoo46** [comment]
Thanks!
