### ISSUE TITLE
All the detected variants with genotype missing

### ISSUE THREAD

**Issue by ivangalvan** [jewmanchue/wham#46]
Hi Zev,

I have installed the last version of wham available from: http://zeeev.github.io/wham/

When I run wham, all the detected variants have missing genotypes. I run the same bam file with other variant callers (GATK, deepvariant, manta, freebayes, etc) and all of them generate genotypes.

See, please, the commands and outputs below, I made something wrong? 

Thank you,

Ivan

###############

command:

whamg -x 48 -a human_ref_bwa_0.7.5a/hg19.fa -f insilico15_all_tumor.markdups.bam > wham/insilico_2/insilico2_tumor.vcf 2> wham/insilico_2/insilico2_tumor.err 

head output /insilico2_tumor.vcf:

##fileformat=VCFv4.2
##source=WHAM-GRAPHENING:v1.7.0-311-g4e8c
##reference=human_ref_bwa_0.7.5a/hg19.fa
##INFO=<ID=A,Number=1,Type=Integer,Description="Total pieces of evidence">
##INFO=<ID=CIEND,Number=2,Type=Integer,Description="Confidence interval around END for imprecise variants">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS for imprecise variants">
##INFO=<ID=CF,Number=1,Type=Float,Description="Fraction of reads in graph that cluster with SVTYPE pattern">
##INFO=<ID=CW,Number=5,Type=Float,Description="SVTYPE weight 0-1; DEL,DUP,INV,INS,BND">
##INFO=<ID=D,Number=1,Type=Integer,Description="Number of reads supporting a deletion">
##INFO=<ID=DI,Number=1,Type=Float,Description="Average distance of mates to breakpoint">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=EV,Number=1,Type=Integer,Description="Number everted mate-pairs">
##INFO=<ID=I,Number=1,Type=Integer,Description="Number of reads supporting an insertion">
##INFO=<ID=SR,Number=1,Type=Integer,Description="Number of split-reads supporing SV">
##INFO=<ID=SS,Number=1,Type=Integer,Description="Number of split-reads supporing SV">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=T,Number=1,Type=Integer,Description="Number of reads supporting a BND">
##INFO=<ID=TAGS,Number=.,Type=String,Description="SM tags with breakpoint support">
##INFO=<ID=TF,Number=1,Type=Integer,Description="Number of reads mapped too far">
##INFO=<ID=U,Number=1,Type=Integer,Description="Number of reads supporting a duplication">
##INFO=<ID=V,Number=1,Type=Integer,Description="Number of reads supporting an inversion">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=SP,Number=1,Type=Integer,Description="Per sample SV support">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  insil
1       7570071 .       A       <DEL>   .       PASS    A=11;CIEND=-10,10;CIPOS=-10,10;CF=1;CW=0.727273,0.272727,0,0,0;D=8;DI=395.75;END=7571511;EV=0;I=0;SR=3;SS=0;SVLEN=-1440;SVTYPE=DEL;T=0;TAGS=insil;TF=5;U=3;V=0    **GT:DP:SP**        **.:.:10**
1       8180881 .       A       <DUP>   .       PASS    A=45;CIEND=-10,10;CIPOS=-10,10;CF=1;CW=0.355556,0.577778,0,0.0666667,0;D=16;DI=0;END=47694139;EV=6;I=3;SR=20;SS=0;SVLEN=39513258;SVTYPE=DUP;T=0;TAGS=insil;TF=6;U=26;V=0  **GT:DP:SP**        **.:.:42**
1       8381454 .       A       <INS>   .       PASS    A=13;CIEND=-10,10;CIPOS=-10,10;CF=0;CW=0,0.0769231,0,0.923077,0;D=0;DI=0;END=8381454;EV=0;I=12;SR=1;SS=0;SVLEN=20;SVTYPE=INS;T=0;TAGS=insil;TF=0;U=1;V=0  **GT:DP:SP        .:.:20**

**Comment by zeeev** [comment]
Hi @ivangalvan,

Whamg doesn't genotype SVs. However, you can genotype these events with: https://github.com/hall-lab/svtyper 

Best,

Zev
