### ISSUE TITLE
Bam file not being read

### ISSUE THREAD

**Issue by drashwinelkar** [jewmanchue/wham#57]
I am running whamg of the docker container : wham:1.8.0.1.2017.05.03--hd28b015_0
I have provided and index and sorted bam file which is the output of bwa mem with the -R option.

I get the following error when I run whamg-
INFO: fasta file: ChAdOx1nCov19_scaffolds_RC.fa
INFO: gathering stats (may take some time) for bam: DNA2_wham_sorted.bam
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)

My read length is 75 bp, paired end sequencing.
I tried switching the docker versions but I get the same error, it must be something with my bam file.
The bam file is perfectly valid for other SV calling tools that need it.

**Comment by zeeev** [comment]
My reply is too late to be useful, but it could be a ref file mismatch?
